### ISSUE TITLE
Inference?

### ISSUE THREAD

**Issue by Timothy199707** [cindyxinyiwang/TextStyleTransfer#11]
I was trying to use the model for certain translation/style transfer project, while it showing great performance in our dev set in eval(), I had failed to recreate the same result in inference with the Seq2Seq model. Is there a specific technic (aside beam search of course) the model did during the eval part? For example, utilizing the LM during the beam search?

I would love to give u my code ... but currently it's way too messy, I was using the function translate() in model.py, could it be that I'm missing the x_pos_emb_idxs and y_pos_emb_idxs (for model.forward) lead to the failure for recreation?

**Comment by jxhe** [comment]
Hi,

`x_pos_emb_idxs` and `y_pos_emb_idxs` are not actually used in model.forward, thus they should not be the reason. This repo contains script to translate at inference time, can you  refer to `scripts/translate.sh` for the example script and https://github.com/cindyxinyiwang/deep-latent-sequence-model/blob/8a798582b1af5ef7f6ac4ca1f2138fd382a1cb06/scripts/yelp/eval_all.sh#L29 on how to run it?

**Comment by Timothy199707** [comment]
Thanks, although I haven't found my bug, I managed to change to code using similar ways in scripts/translate.sh
Have a nice day!
