### ISSUE TITLE
how to use multi-gpu for training

### ISSUE THREAD

**Issue by NingHongKe** [cindyxinyiwang/TextStyleTransfer#12]
I'm wondering how to use multi-gpu for training.
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

![image](https://user-images.githubusercontent.com/3986048/106105116-6bf62880-617e-11eb-9469-fc3f2b6d60c7.png)

**Comment by jxhe** [comment]
Sorry the code doesn't support multi-gpu training
