### ISSUE TITLE
A question about language model priors

### ISSUE THREAD

**Issue by seongminp** [cindyxinyiwang/TextStyleTransfer#14]
_[Sorry for the duplicate mess.. I closed my original issue by accident..]_

Hi. Thank you for such an exciting paper!

I ran into some hurdles while trying to adopt your methodology to a task of my own.

I would appreciate it greatly if you could shed some light on these:

1. The biggest question for me is how exactly we align an observed sequence in domain 1 (D1) to its corresponding latent sequence in domain 2 (D2). I guess the alignment is found through optimizing the KL regularizer (equation 3 in paper).  
In the log_prior calculation, 
https://github.com/cindyxinyiwang/deep-latent-sequence-model/blob/8a798582b1af5ef7f6ac4ca1f2138fd382a1cb06/src/model.py#L339

the log_prior is calculated as a combination of the output of both LMs. Is there a reason you are calculating KL = E_{x ~ q(z|x, y)}[log q(z|x, y) - log p(z|y)] instead of KL = E_{x ~ q(z|x)}[log q(z|x) - log p(z)], like in the paper? If this is due to parameter sharing, is z here a representation of both latent x and y? (a concatenation, maybe?)

2. When loading train data, is there a reason `y` is sampled with `1-y_train`? :
https://github.com/cindyxinyiwang/deep-latent-sequence-model/blob/8a798582b1af5ef7f6ac4ca1f2138fd382a1cb06/src/data_utils.py#L99

3. Is there a reason only latent y (and not x, from the other domain) is sampled in the data loading process? From equation 3 I presumed we sample from both domains to compare to each lm separately.

Thank you!

**Comment by jxhe** [comment]
Hi,

There are some inconsistent notations between the code and the paper -- in the paper y denotes the observed data from domain D2, while in the code y is a binary variable corresponding to the domain id of the data sample. In other words, in the code x represents all the observed data (can be from either domain D1 or D2), and y represents a binary indicator of the domains. Maybe some confusion of your questions would be cleared up after this:

1. I believe that we are calculating what is written in the paper -- the notations are a bit different as mentioned
2. `y_sampled` is used during the back-translation stage to translate data samples to the other domain (and we need to later translate it back) as shown in Figure 2 of the paper. Thus the binary indicator (i.e. y) needs to be reversed 
3. I think this question is cleared up after sorting out the inconsistent notations

**Comment by seongminp** [comment]
Oh.. that makes sense!

Thanks a lot!
