### ISSUE TITLE
Why do we need parallel sentences in the datsets?

### ISSUE THREAD

**Issue by Vicky-Shao** [cindyxinyiwang/TextStyleTransfer#19]
Hello, this paper says it works in a completely unsupervised fasion. But I see the files 'train.txt' and 'dev.txt' in datasets have parallel sentences from two domains. What's the function of these parallel sentences? And if I want to complete the training in a new style with completely non-parallel sentences, how can I do? Thanks very much!
[train.txt](https://github.com/cindyxinyiwang/deep-latent-sequence-model/files/8286344/train.txt)

**Comment by jxhe** [comment]
Hi, the code never reads parallel sentences -- the code would treat the given sentences from two domains unpaired even though you give the code parallel sentences. The data file you mentioned is the shakespeare dataset, which we borrowed from a supervised parallel dataset, but the code doesn't use this parallel information. The code reads one domain a time, and never pairs the examples from two domains -- actually the code would still work even though train_0.txt and train_1.txt have different lines.

You may take a look at other datasets such as the yelp dataset, where train_0.txt and train_1.txt are not parallel. 

To complete the training in a new style, just prepare train/dev/test_0.txt from domain 0, one example per line, and prepare train/dev/test_1.txt from domain 1, one example per line. It doesn't really matter whether they are parallel or not.

**Comment by Vicky-Shao** [comment]
I check the other datasets and find parallel corpus in shakespeare is a special case. Thanks for your reply and datailed explanation!
