### ISSUE TITLE
Cant find intial reconstruction loss code

### ISSUE THREAD

**Issue by drumilT** [cindyxinyiwang/TextStyleTransfer#4]
The paper mentions that you used initially for k epochs, a reconstruction loss. However I could find it, could you point me to it please?

**Comment by jxhe** [comment]
https://github.com/cindyxinyiwang/deep-latent-sequence-model/blob/8bbc71ff2bf856cafcf97a3174cf4869a21a9eff/src/utils.py#L75

Here the noise_loss is the reconstruction loss mentioned in the paper
