### ISSUE TITLE
Problems about reproducing decipher

### ISSUE THREAD

**Issue by hzhwcmhf** [cindyxinyiwang/TextStyleTransfer#5]
The first problem is the link to download LM.

https://github.com/cindyxinyiwang/deep-latent-sequence-model/blob/05860a09af451a5ec429c2aa6d710f31e381007b/scripts/prepare_lm.py#L59

This line seems to use `decipher_id`

The second problem is the code for evaluation.

https://github.com/cindyxinyiwang/deep-latent-sequence-model/blob/05860a09af451a5ec429c2aa6d710f31e381007b/scripts/decipher/eval_all.sh#L2

There is not a file at `./scripts/translate.sh`

**Comment by jxhe** [comment]
Should be resolved now : )

**Comment by hzhwcmhf** [comment]
Thanks!
