### ISSUE TITLE
Resource requirement and multiple conditioning

### ISSUE THREAD

**Issue by riven314** [cindyxinyiwang/TextStyleTransfer#8]
Thanks for the great work!

May I know how many GPUs (and how many GB) do I need to train the model? 
Apart from that, could the model do multiple attributes conditioning? (e.g. condition on both sentence length, writer style and sentiment)

**Comment by jxhe** [comment]
Hi, we were using one 12GB GPU to train the model on our datasets. And the current version of code  only supports one attribute

**Comment by riven314** [comment]
thanks!
