### ISSUE TITLE
cnn_classify.py: error: unrecognized arguments: --data_path data/test/

### ISSUE THREAD

**Issue by mohit2agrawal** [cindyxinyiwang/TextStyleTransfer#9]
I get the following error while executing the yelp eval_all.sh.
Command I ran: `bash scripts/yelp/eval_all.sh outputs_yelp/yelp_wd0.0_wb0.0_ws0.0_an3_pool5_klw0.1_lr0.001_t0.01_lm_bt_hard_avglen`

Error:
**`cnn_classify.py: error: unrecognized arguments: --data_path data/test/`**

`scripts/yelp/eval_all.sh` calls `scripts/yelp/yelp_classify_test.sh` which further calls `src/cnn_classify.py` resulting in the error above.
What should be the correct argument?

**Comment by mohit2agrawal** [comment]
Currently its working by just removing that line.

**Comment by jxhe** [comment]
Thanks for the catch! Yeah you just need to remove that line, we have fixed that
